// @ts-nocheck
"use client"
const Z=["CEMAC","UEMOA","Dollar","Jordanie","Golfe","Moyen-Orient","International"]
const B={"CEMAC":["Afriland","UBA Tchad","BGFI"],"UEMOA":["BOA","Ecobank"],"Dollar":["Chase","BofA"],"Jordanie":["Arab Bank"],"Golfe":["ADCB","Al Rajhi"],"Moyen-Orient":["Bank Audi"],"International":["BNP","Deutsche"]}
const MON=["PI-314159 USD","XAF","XOF","USD","EUR","AED","JOD","BTC","USDT"]
const POOLS=[["Pi/USDT","2.4M","12.5%"],["Pi/BTC","1.8M","10.2%"],["Pi/ETH","2.1M","11%"],["Pi/XAF","3.2M","7.5%"],["Pi/XOF","2.8M","7.2%"]]
export function Transferer({gdb}){
const [tab,setTab]=useState("INTERNE"),[zone,setZone]=useState("CEMAC")
return (<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{display:"flex",gap:4}}><button onClick={()=>setTab("INTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="INTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="INTERNE"?"#dbeafe":"#fff",fontWeight:800}}>P2P INTERNE</button><button onClick={()=>setTab("EXTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="EXTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="EXTERNE"?"#dbeafe":"#fff",fontWeight:800}}>P2P EXTERNE</button></div>
{tab==="INTERNE"?(<div style={{display:"flex",flexDirection:"column",gap:6}}><input placeholder="Numéro du Compte Bancaire" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(m=><option key={m}>{m}</option>)}</select><input placeholder="Montant à envoyer" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input placeholder="Motif (Optionnel)" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Envoyer • {gdb.slice(0,10)}</button><div style={{fontSize:9,color:"#16a34a",background:"#f0fdf4",padding:6,borderRadius:6,textAlign:"center"}}>Les transactions sont instantanées et interopérables.</div></div>):(<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map(z=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{B[zone].map(b=><option key={b}>{b}</option>)}</select><input placeholder="Entrer le numéro de compte" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(m=><option key={m}>{m}</option>)}</select><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Transférer Vers Banque Externe • ISO20022 SWIFT SEPA</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>Transfert instantané via système interopérable</div></div>)}
</div>)}
export function Virement({gdb}){const [zone,setZone]=useState("CEMAC"); return (<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map(z=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{B[zone].map(b=><option key={b}>{b}</option>)}</select><input placeholder="Numéro de compte" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(m=><option key={m}>{m}</option>)}</select><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Traiter l'opération • {gdb.slice(0,10)}</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>Le Virement est instantané dans le système interopérable.</div></div>)}
export function PiDex({gdb}){const [pool,setPool]=useState(POOLS[0]),[slip,setSlip]=useState("0.5%"); return (<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontSize:9,color:"#64748b"}}>PiCoin référence • Frais 0.3% + {gdb} • Slip 0.5%/1%/3%</div><div style={{display:"flex",gap:4}}>{["0.5%","1%","3%"].map(s=><button key={s} onClick={()=>setSlip(s)} style={{padding:"4px 8px",borderRadius:20,border:slip===s?"2px solid #1e40af":"1px solid #e2e8f0",background:slip===s?"#dbeafe":"#fff",fontSize:9,fontWeight:800}}>{s}</button>)}</div><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Swap via AMM • {slip} • {gdb.slice(0,10)}</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>AMM instantané • interopérable • sécurisé de bout en bout</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{POOLS.map(p=><button key={p[0]} onClick={()=>setPool(p)} style={{textAlign:"left",padding:8,borderRadius:10,border:pool[0]===p[0]?"2px solid #1e40af":"1px solid #e2e8f0",background:pool[0]===p[0]?"#dbeafe":"#fff"}}><div style={{fontWeight:900,fontSize:10}}>{p[0]}</div><div style={{fontSize:8}}>Liq {p[1]} • APY {p[2]}</div></button>)}</div></div>)}
export function Convertir(){return <div>Convertisseur 100+ Devises Mondiales • PI XAF XOF USD EUR BTC etc • Taux temps reel</div>}
export function Trading(){return <div>Trading 10+ Paires en temps réel • Chart • Pi/USDT, Pi/BTC</div>}
export function AIAuto(){return <div>AI Auto • Trading automatique • Monitoring Intelligent</div>}
export function Blockchain(){return <div>Blockchain • Explorer • ISO20022 • PI 314159 USD • {Date.now()}</div>}
export function Shopping(){return <div>Shopping • E-commerce 10+ Plateformes Mondiales • Payer en Pi</div>}
export function Portefeuilles(){return <div>Portefeuilles • Crypto & Digital • Multi-devises</div>}
export function Automobile(){return <div>Partenariat Automobile • 18+ Marques Disponibles • Payer en Pi</div>}
export function Agregation(){return <div>Agrégation • Agrégateur de liquidités</div>}
export function Gestion(){return <div>Gestion • Gestion de compte avancée</div>}
// Pour eviter erreur useState dans ce fichier
import { useState } from "react"
