"use client"
import { useState, useEffect } from "react"
export const Z=["CEMAC","UEMOA","Dollar","Jordanie","Golfe","Moyen-Orient","International"]
export const BANKS={
"CEMAC":["Afriland First Bank Cameroun","Commercial Bank Tchad","UBA Tchad","BGFI Gabon","BICEC","Ecobank CEMAC","CBC","SGBC"],
"UEMOA":["BOA Senegal","Ecobank CI","Coris BF","NSIA Benin","Banque Atlantique","BCEAO"],
"Dollar":["Chase USA","Bank of America","Citi USA","Wells Fargo"],
"Jordanie":["Arab Bank Jordan","Jordan Islamic Bank","Cairo Amman Bank"],
"Golfe":["ADCB UAE","Al Rajhi Saudi","QNB Qatar","NBK Kuwait","FAB UAE"],
"Moyen-Orient":["Bank Audi Liban","Bank of Palestine","National Bank Egypt"],
"International":["BNP France","Deutsche Bank","HSBC UK","Santander"]
}
const RATES:any={USD:314159,EUR:290000,XAF:190000000,XOF:190000000,AED:1150000,JOD:222000,BTC:4.8,ETH:98,USDT:314159,USDC:314159}
export function Transferer({gdb}:{gdb:string}){
const [tab,setTab]=useState("INTERNE")
const [zone,setZone]=useState("CEMAC")
return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{display:"flex",gap:4}}><button onClick={()=>setTab("INTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="INTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="INTERNE"?"#dbeafe":"#fff",fontWeight:800}}>P2P INTERNE</button><button onClick={()=>setTab("EXTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="EXTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="EXTERNE"?"#dbeafe":"#fff",fontWeight:800}}>P2P EXTERNE</button></div>{tab==="INTERNE"?<><input placeholder="Numero Compte GDB" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Envoyer {gdb.slice(0,10)}</button></>:<><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map((z:string)=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{BANKS[zone as keyof typeof BANKS].map((b:string)=><option key={b}>{b}</option>)}</select><input placeholder="Numero compte externe" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Transferer Externe</button></>}<div style={{fontSize:9,color:"#16a34a",background:"#f0fdf4",padding:6,borderRadius:6,textAlign:"center"}}>Instantane interop ISO20022 SWIFT SEPA</div></div>)}
export function Virement({gdb}:{gdb:string}){const [zone,setZone]=useState("CEMAC"); return(<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map((z:string)=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{BANKS[zone as keyof typeof BANKS].map((b:string)=><option key={b}>{b}</option>)}</select><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Traiter operation</button></div>)}
export function PiDex({gdb}:{gdb:string}){const pools=[["Pi/USDT","2.4M","12.5%"],["Pi/BTC","1.8M","10.2%"],["Pi/ETH","2.1M","11%"],["Pi/USDC","1.9M","9.8%"],["Pi/SOL","800K","12%"],["Pi/ADA","890K","13.2%"],["Pi/XLM","620K","8.5%"],["Pi/XRP","1.2M","9.2%"],["Pi/MATIC","980K","10.8%"],["Pi/BNB","1.5M","11.5%"]]; const [pool,setPool]=useState(pools[0]); const [slip,setSlip]=useState("0.5%"); return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:800}}>Pi DEX AMM PiCoin reference</div><div style={{display:"flex",gap:4}}>{["0.5%","1%","3%"].map((s:string)=><button key={s} onClick={()=>setSlip(s)} style={{padding:"4px 8px",borderRadius:20,border:slip===s?"2px solid #1e40af":"1px solid #e2e8f0",background:slip===s?"#dbeafe":"#fff",fontSize:9,fontWeight:800}}>{s}</button>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{pools.map((p:any)=><button key={p[0]} onClick={()=>setPool(p)} style={{textAlign:"left",padding:8,borderRadius:10,border:pool[0]===p[0]?"2px solid #1e40af":"1px solid #e2e8f0",background:pool[0]===p[0]?"#dbeafe":"#fff"}}><div style={{fontWeight:900,fontSize:10}}>{p[0]}</div><div style={{fontSize:8}}>Liq {p[1]} APY {p[2]}</div></button>)}</div><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Swap via AMM {pool[0]} {slip} {gdb.slice(0,10)}</button></div>)}
export function ConvertirComp(){const [to,setTo]=useState("USD"); const [amt,setAmt]=useState(1); const [live,setLive]=useState(314159); useEffect(()=>{const id=setInterval(()=>setLive(RATES[to]*(0.99+Math.random()*0.02)),1000); return()=>clearInterval(id)},[to]); return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Convertisseur Devises 1 pi=314159 USD GCV</div><div style={{fontSize:9,color:"#16a34a",background:"#f0fdf4",padding:6,borderRadius:6}}>Synchro chaque seconde Live 1 PI={live.toFixed(2)} {to}</div><div style={{display:"flex",gap:6}}><select style={{flex:1,padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}><option>PI</option></select><select value={to} onChange={(e)=>setTo(e.target.value)} style={{flex:1,padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{Object.keys(RATES).map((k:string)=><option key={k}>{k}</option>)}</select></div><input type="number" value={amt} onChange={(e:any)=>setAmt(e.target.value)} style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><div style={{background:"#f8fafc",padding:10,borderRadius:8,fontWeight:800}}>{amt} PI = {(amt*(RATES[to])).toFixed(2)} {to}</div><div style={{display:"flex",gap:6}}><button style={{flex:1,padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Effectuer Conversion</button><button style={{flex:1,padding:10,borderRadius:10,background:"#16a34a",color:"#fff",fontWeight:900,border:"none"}}>Deposer sur Carte</button></div></div>)}
export function TradingComp(){const pairs=["PI/BTC","PI/USDT","PI/USDC","PI/ETH","PI/SOL","PI/ADA","PI/XLM","PI/XRP","PI/MATIC","PI/BNB","PI/AVA","PI/DOT","PI/TRX"]; const [p,setP]=useState("PI/USDT"); return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Trading Pi Network 1 pi=314159 USD GCV</div><div style={{fontSize:9,color:"#16a34a",background:"#f0fdf4",padding:6,borderRadius:6}}>Synchro temps reel chaque seconde {p} Live</div><div style={{display:"flex",gap:4,overflowX:"auto"}}>{pairs.map((x:string)=><button key={x} onClick={()=>setP(x)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:p===x?"2px solid #1e40af":"1px solid #e2e8f0",background:p===x?"#1e40af":"#fff",color:p===x?"#fff":"#000",fontSize:9,fontWeight:800}}>{x}</button>)}</div><div style={{background:"#111",color:"#22c55e",padding:12,borderRadius:10,fontSize:10,fontFamily:"monospace"}}>Chart {p} 314159 USD +2.4% TPS 1200</div></div>)}
export function AIAutoComp(){return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>IA Automatisation Outils no-code</div><div style={{fontSize:10}}>Assistant IA 24/7, Recommandations, Detection Fraude IA, Categorisation Auto</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}><div style={{border:"1px solid #e2e8f0",padding:8,borderRadius:8}}><div style={{fontSize:10,fontWeight:800}}>Paiement Auto</div><button style={{marginTop:4,padding:6,borderRadius:6,background:"#1e40af",color:"#fff",border:"none",fontSize:9}}>Configurer</button></div><div style={{border:"1px solid #e2e8f0",padding:8,borderRadius:8}}><div style={{fontSize:10,fontWeight:800}}>Epargne Auto</div><button style={{marginTop:4,padding:6,borderRadius:6,background:"#1e40af",color:"#fff",border:"none",fontSize:9}}>Configurer</button></div><div style={{border:"1px solid #e2e8f0",padding:8,borderRadius:8}}><div style={{fontSize:10,fontWeight:800}}>Rappel Factures</div><button style={{marginTop:4,padding:6,borderRadius:6,background:"#16a34a",color:"#fff",border:"none",fontSize:9}}>Activer</button></div><div style={{border:"1px solid #e2e8f0",padding:8,borderRadius:8}}><div style={{fontSize:10,fontWeight:800}}>Echange Auto</div><button style={{marginTop:4,padding:6,borderRadius:6,background:"#16a34a",color:"#fff",border:"none",fontSize:9}}>Activer</button></div></div></div>)}
export function BlockchainComp(){return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Blockchain Web 3.0 Innovation</div><div style={{display:"flex",gap:6}}><div style={{flex:1,background:"#1e40af",color:"#fff",padding:8,borderRadius:8,textAlign:"center"}}><div style={{fontSize:9}}>Transactions</div><div style={{fontWeight:900}}>987654</div></div><div style={{flex:1,background:"#111",color:"#facc15",padding:8,borderRadius:8,textAlign:"center"}}><div style={{fontSize:9}}>Blocs</div><div style={{fontWeight:900}}>123456</div></div><div style={{flex:1,background:"#16a34a",color:"#fff",padding:8,borderRadius:8,textAlign:"center"}}><div style={{fontSize:9}}>TPS</div><div style={{fontWeight:900}}>1200</div></div></div><div style={{fontSize:10}}>Monnaies Golfe CCG AED SAR QAR KWD OMR BHD</div><div style={{fontSize:10}}>Blockchains Actives PI Bitcoin Solana Ethereum Ripple Stellar Cardano Binance</div></div>)}
export function ShoppingComp(){const sites=["Amazon","Alibaba","Noon","Jumia","AliExpress","eBay","Shein","Temu","Carrefour","Walmart"]; return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Shopping 10+ Plateformes Mondiales</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{sites.map((s:string)=><div key={s} style={{border:"1px solid #e2e8f0",padding:8,borderRadius:8}}><div style={{fontWeight:800,fontSize:10}}>{s}</div><div style={{fontSize:8,color:"#64748b"}}>Article en Pi GCV</div><div style={{display:"flex",gap:4,marginTop:4}}><button style={{flex:1,padding:4,borderRadius:6,background:"#1e40af",color:"#fff",border:"none",fontSize:8}}>Acheter</button><button style={{flex:1,padding:4,borderRadius:6,background:"#fff",border:"1px solid #1e40af",color:"#1e40af",fontSize:8}}>Commander</button></div></div>)}</div></div>)}
export function PortefeuilleComp({gdb,rcv}:{gdb:string,rcv:string}){return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Portefeuille Gestion Actifs</div><div style={{background:"#1e40af",color:"#fff",padding:10,borderRadius:10}}><div style={{fontSize:10}}>Solde {gdb}</div><div style={{fontWeight:900,marginTop:4}}>1 PI=314159 USD 2.4 Pi 12.5k XAF</div></div><div style={{display:"flex",gap:6}}><button style={{flex:1,padding:8,borderRadius:8,background:"#16a34a",color:"#fff",border:"none",fontWeight:800}}>Envoyer</button><button style={{flex:1,padding:8,borderRadius:8,background:"#fff",border:"1px solid #1e40af",color:"#1e40af",fontWeight:800}}>Recevoir {rcv.slice(0,8)}</button></div></div>)}
export function AutomobileComp(){return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Automobile Partenaire Mondial</div><div style={{fontSize:10}}>GDB partenaire Toyota Mercedes BMW Tesla Hyundai 18+ marques</div><div style={{background:"#f8fafc",border:"1px solid #e2e8f0",padding:8,borderRadius:8}}><div style={{fontWeight:800,fontSize:10}}>Calculateur IA Dedouanement Temps Reel</div><input placeholder="Pays destination" style={{width:"100%",marginTop:6,padding:8,borderRadius:6,border:"1px solid #cbd5e1"}}/><input placeholder="Valeur vehicule USD" style={{width:"100%",marginTop:4,padding:8,borderRadius:6,border:"1px solid #cbd5e1"}}/><button style={{marginTop:6,padding:8,borderRadius:8,background:"#1e40af",color:"#fff",border:"none",fontWeight:800,width:"100%"}}>Calculer Frais Auto</button></div><button style={{padding:8,borderRadius:8,background:"#fff",border:"1px solid #1e40af",color:"#1e40af",fontWeight:800}}>Creer Compte Concessionnaire Agree</button></div>)}
export function AgregationComp(){return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Agregation Gestion Tous Comptes</div><div style={{fontSize:10}}>Connectez Banque Mobile Money Crypto Pi Vue unique</div><button style={{padding:8,borderRadius:8,background:"#1e40af",color:"#fff",border:"none",fontWeight:800}}>Agreger Mes Comptes</button></div>)}
export function GestionComp(){return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Gestion Financiere Intelligente</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,fontSize:10}}><div style={{background:"#dbeafe",padding:8,borderRadius:8}}>Shopping 40%</div><div style={{background:"#fef3c7",padding:8,borderRadius:8}}>Alimentation 20%</div><div style={{background:"#f0fdf4",padding:8,borderRadius:8}}>Habillement 10%</div><div style={{background:"#fee2e2",padding:8,borderRadius:8}}>Sante 10%</div></div></div>)}
export function Cartes({gdb,rcv}:{gdb:string,rcv:string}){
const [type,setType]=useState("Virtuelle")
const [pay,setPay]=useState("Pi")
const [showCvv,setShowCvv]=useState(false)
const [balance,setBalance]=useState("0")
return(<div style={{display:"flex",flexDirection:"column",gap:10}}><div style={{display:"flex",gap:6}}><button onClick={()=>setType("Virtuelle")} style={{flex:1,padding:8,borderRadius:10,border:type==="Virtuelle"?"2px solid #1e40af":"1px solid #e2e8f0",background:type==="Virtuelle"?"#dbeafe":"#fff",fontWeight:800}}>Virtuelle</button><button onClick={()=>setType("Physique")} style={{flex:1,padding:8,borderRadius:10,border:type==="Physique"?"2px solid #1e40af":"1px solid #e2e8f0",background:type==="Physique"?"#dbeafe":"#fff",fontWeight:800}}>Physique</button></div>
<div style={{background:type==="Virtuelle"?"linear-gradient(135deg,#1e40af,#3b82f6)":"linear-gradient(135deg,#111,#444)",color:"#fff",borderRadius:16,padding:14,minHeight:170}}>
<div style={{display:"flex",justifyContent:"space-between"}}><div style={{fontSize:10}}>GARGOURA DIGITAL BANK</div><div style={{fontSize:10}}>{type.toUpperCase()} PI</div></div><div style={{marginTop:14,display:"flex",gap:8}}><div style={{width:32,height:22,background:"#facc15",borderRadius:4}}></div></div><div style={{fontFamily:"monospace",fontSize:14,letterSpacing:2,marginTop:10}}>4242 4242 {type==="Virtuelle"?"4334":"6262"}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:12}}><div><div style={{fontSize:8,color:"#cbd5e1"}}>TITULAIRE</div><div style={{fontSize:10,fontWeight:800}}>{gdb.slice(0,12)}</div></div><div><div style={{fontSize:8,color:"#cbd5e1"}}>EXP</div><div style={{fontSize:10}}>12/29</div></div><div><div style={{fontSize:8,color:"#cbd5e1"}}>CVV</div><div style={{fontSize:10}} onClick={()=>setShowCvv(!showCvv)}>{showCvv?"123":"***"}</div></div></div></div>
<div style={{display:"flex",gap:6}}><input type="number" placeholder="Montant recharge" onChange={(e:any)=>setBalance(e.target.value)} style={{flex:1,padding:8,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:8,borderRadius:8,background:"#16a34a",color:"#fff",border:"none",fontWeight:800}}>Recharger {balance} Pi</button></div>
<div style={{display:"flex",gap:4}}><button onClick={()=>setPay("Pi")} style={{flex:1,padding:8,borderRadius:8,border:pay==="Pi"?"2px solid #1e40af":"1px solid #e2e8f0",background:pay==="Pi"?"#dbeafe":"#fff",fontSize:10,fontWeight:800}}>Payer en Pi</button><button onClick={()=>setPay("MobileMoney")} style={{flex:1,padding:8,borderRadius:8,border:pay==="MobileMoney"?"2px solid #1e40af":"1px solid #e2e8f0",background:pay==="MobileMoney"?"#dbeafe":"#fff",fontSize:10,fontWeight:800}}>Mobile Money</button></div>
<button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Acheter Activer {type} via {pay}</button><div style={{fontSize:9,color:"#64748b"}}>{type==="Virtuelle"?"Activation instantanee":"Activation 3-7 jours par Admin anti-fraude"} QR {rcv.slice(0,12)}</div></div>)}
export function KYCComp({gdb,onVerified}:{gdb:string,onVerified:any}){
const [addr,setAddr]=useState("")
const [user,setUser]=useState("")
function verify(){
if(!addr.startsWith("G")||addr.length<10){alert("Adresse Pi doit commencer par G"); return}
if(!user){alert("Username Pi requis"); return}
localStorage.setItem("gdb_pi_addr",addr)
localStorage.setItem("gdb_pi_user",user)
localStorage.setItem("gdb_kyc_verified","true")
onVerified && onVerified(user)
alert("KYC Verifie "+user)
}
return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>KYC Officiel GDB Lie Pi Network</div><div style={{fontSize:10,color:"#dc2626",background:"#fef2f2",border:"1px solid #fecaca",padding:8,borderRadius:8,fontWeight:800}}>Gargoura ne demande JAMAIS votre Phrase Secrete ou Cle Secrete. Ne partagez jamais vos 24 mots.</div><input value={addr} onChange={(e:any)=>setAddr(e.target.value)} placeholder="Adresse publique Pi G..." style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input value={user} onChange={(e:any)=>setUser(e.target.value)} placeholder="Username Pi Network" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button onClick={verify} style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Verifier Statut KYC Pi Officiel {gdb.slice(0,8)}</button></div>)}
