// @ts-nocheck
"use client"
import { useState } from "react"
export const Z=["CEMAC","UEMOA","Dollar","Jordanie","Golfe","Moyen-Orient","International"]
export const BANKS={
"CEMAC":["Afriland First Bank Cameroun","Commercial Bank Tchad","UBA Tchad","BGFI Gabon","BICEC Cameroun","Ecobank CEMAC","BANGE Cameroun","CBC Cameroun","SGBC","BICIG Gabon"],
"UEMOA":["BOA Senegal","Ecobank CI","Coris Bank BF","NSIA Benin","Banque Atlantique Togo","BCEAO","UBA Senegal","Ecobank Mali","BOA Niger","Banque Atlantique CI"],
"Dollar":["Chase Bank USA","Bank of America","Citi Bank USA","Wells Fargo","HSBC USA","Capital One USA"],
"Jordanie":["Arab Bank Jordan","Jordan Islamic Bank","Cairo Amman Bank","Jordan Kuwait Bank","Housing Bank Jordan"],
"Golfe":["ADCB UAE","Al Rajhi Saudi","QNB Qatar","NBK Kuwait","Ahli Bank Oman","FAB UAE","Emirates NBD","SNB Saudi"],
"Moyen-Orient":["Bank Audi Liban","BLOM Liban","Bank of Palestine","National Bank Egypt","Bank of Jordan","Audi Jordan"],
"International":["BNP Paribas France","Deutsche Bank Germany","HSBC UK","Santander Spain","Barclays UK","Credit Agricole","Societe Generale","UBS Switzerland"]
}
export const MON=["PI - 314159 USD","XAF CEMAC","XOF UEMOA","USD","EUR","AED","JOD","BTC","USDT","USDC"]
export const POOLS=[
["Pi/USDT","2.4M","12.5%"],["Pi/BTC","1.8M","10.2%"],["Pi/ETH","2.1M","11%"],["Pi/USDC","1.9M","9.8%"],["Pi/ADA","890K","13.2%"],["Pi/DOT","750K","14.1%"],["Pi/XLM","620K","8.5%"],["Pi/XRP","1.2M","9.2%"],["Pi/MATIC","980K","10.8%"],["Pi/BNB","1.5M","11.5%"],["Pi/AVA","430K","15%"],["Pi/TRX","560K","9%"],["Pi/XAF","3.2M","7.5%"],["Pi/XOF","2.8M","7.2%"],["Pi/EUR","2M","8%"]
]
export function Transferer({gdb}){const [tab,setTab]=useState("INTERNE"),[zone,setZone]=useState("CEMAC"); return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{display:"flex",gap:4}}><button onClick={()=>setTab("INTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="INTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="INTERNE"?"#dbeafe":"#fff",fontWeight:800}}>P2P INTERNE</button><button onClick={()=>setTab("EXTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="EXTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="EXTERNE"?"#dbeafe":"#fff",fontWeight:800}}>P2P EXTERNE</button></div>{tab==="INTERNE"?(<div style={{display:"flex",flexDirection:"column",gap:6}}><input placeholder="Numéro du Compte Bancaire GDB" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(m=><option key={m}>{m}</option>)}</select><input placeholder="Montant à envoyer" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input placeholder="Motif (Optionnel)" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Envoyer • {gdb.slice(0,10)}</button><div style={{fontSize:9,color:"#16a34a",background:"#f0fdf4",padding:6,borderRadius:6,textAlign:"center"}}>Les transactions sont instantanées et interopérables.</div></div>):(<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map(z=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{BANKS[zone].map(b=><option key={b}>{b}</option>)}</select><input placeholder="Entrer le numéro de compte externe" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(m=><option key={m}>{m}</option>)}</select><input placeholder="Montant à transférer" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Transférer Vers Banque Externe</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>Transfert instantané via système interopérable - ISO20022 SWIFT SEPA</div></div>)}</div>)}
export function Virement({gdb}){const [zone,setZone]=useState("CEMAC"); return(<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map(z=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{BANKS[zone].map(b=><option key={b}>{b}</option>)}</select><input placeholder="Numéro de compte" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(m=><option key={m}>{m}</option>)}</select><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input placeholder="Motif (Optionnel)" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Traiter l'opération • {gdb.slice(0,10)}</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>Le Virement est instantané dans le système interopérable.</div></div>)}
export function PiDex({gdb}){const [pool,setPool]=useState(POOLS[0]),[slip,setSlip]=useState("0.5%"),[from,setFrom]=useState("PI"),[to,setTo]=useState("USDT"); return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:800}}>Pi DEX & AMM • PiCoin référence</div><div style={{fontSize:9,color:"#64748b"}}>10+ Paires • BTC ETH USDT USDC ADA DOT XLM XRP MATIC BNB AVA TRX • Frais 0.3% + {gdb} • GDB {gdb.slice(0,8)}</div><div style={{display:"flex",gap:4}}>{["0.5%","1%","3%"].map(s=><button key={s} onClick={()=>setSlip(s)} style={{padding:"4px 8px",borderRadius:20,border:slip===s?"2px solid #1e40af":"1px solid #e2e8f0",background:slip===s?"#dbeafe":"#fff",fontSize:9,fontWeight:800}}>{s}</button>)}</div><div style={{background:"#f8fafc",border:"1px solid #e2e8f0",borderRadius:10,padding:8,display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:10,fontWeight:800}}>De</span><span style={{fontSize:10,fontWeight:800}}>{from}</span></div><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><div style={{display:"flex",justifyContent:"center"}}><div style={{background:"#1e40af",color:"#fff",borderRadius:20,width:28,height:28,display:"flex",alignItems:"center",justifyContent:"center"}}>↓</div></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:10,fontWeight:800}}>Vers</span><span style={{fontSize:10,fontWeight:800}}>{to}</span></div><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Swap via AMM {from}→{to} • {slip} • {gdb.slice(0,10)}</button></div><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>AMM instantané • interopérable • sécurisé de bout en bout</div><div style={{fontWeight:800,fontSize:11}}>Pools AMM cliquables • {POOLS.length} pools</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{POOLS.map(p=><button key={p[0]} onClick={()=>{setPool(p); setFrom(p[0].split("/")[0]); setTo(p[0].split("/")[1])}} style={{textAlign:"left",padding:8,borderRadius:10,border:pool[0]===p[0]?"2px solid #1e40af":"1px solid #e2e8f0",background:pool[0]===p[0]?"#dbeafe":"#fff"}}><div style={{fontWeight:900,fontSize:10}}>{p[0]}</div><div style={{fontSize:8,color:"#64748b"}}>Liq {p[1]} • APY {p[2]}</div><div style={{fontSize:7,background:"#1e40af",color:"#fff",borderRadius:8,padding:"2px 5px",width:"fit-content",marginTop:2}}>Pool • Cliquer pour Swap</div></button>)}</div></div>)}
export function Cartes({gdb,rcv}){
const [type,setType]=useState("Virtuelle"),[pay,setPay]=useState("Pi")
return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Cartes Bancaires Virtuelles et Physiques</div><div style={{display:"flex",gap:6}}><button onClick={()=>setType("Virtuelle")} style={{flex:1,padding:8,borderRadius:10,border:type==="Virtuelle"?"2px solid #1e40af":"1px solid #e2e8f0",background:type==="Virtuelle"?"#dbeafe":"#fff",fontWeight:800}}>Virtuelle</button><button onClick={()=>setType("Physique")} style={{flex:1,padding:8,borderRadius:10,border:type==="Physique"?"2px solid #1e40af":"1px solid #e2e8f0",background:type==="Physique"?"#dbeafe":"#fff",fontWeight:800}}>Physique</button></div>
<div style={{background:type==="Virtuelle"?"#1e40af":"#111",color:type==="Virtuelle"?"#fff":"#facc15",borderRadius:12,padding:12}}><div style={{fontSize:10}}>{type} • PI • {gdb}</div><div style={{fontWeight:900,marginTop:8}}>**** **** **** {type==="Virtuelle"?"4334":"6262"}</div><div style={{fontSize:8,marginTop:6}}>Code Réception: {rcv}</div></div>
<div style={{display:"flex",gap:4}}><button onClick={()=>setPay("Pi")} style={{flex:1,padding:8,borderRadius:8,border:pay==="Pi"?"2px solid #1e40af":"1px solid #e2e8f0",background:pay==="Pi"?"#dbeafe":"#fff",fontSize:10,fontWeight:800}}>Payer en Pi (π)</button><button onClick={()=>setPay("MobileMoney")} style={{flex:1,padding:8,borderRadius:8,border:pay==="MobileMoney"?"2px solid #1e40af":"1px solid #e2e8f0",background:pay==="MobileMoney"?"#dbeafe":"#fff",fontSize:10,fontWeight:800}}>Payer Mobile Money</button></div>
<button style={{padding:10,borderRadius:10,background:"#16a34a",color:"#fff",fontWeight:900,border:"none"}}>Acheter & Activer • {type} • via {pay}</button>
<div style={{fontSize:9,color:"#64748b",background:"#f8fafc",padding:6,borderRadius:6}}>{type==="Virtuelle"?"Activation instantanée après paiement":"Activation 3 à 7 jours par Admin GDB pour éviter fraude • Vérification KYC Pi requise"} • GDB {gdb.slice(0,10)}</div>
</div>)}
export function KYCComponent({gdb}){
const [piAddr,setPiAddr]=useState(""),[piUser,setPiUser]=useState("")
return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>KYC Officiel Gargoura Digital Bank • Lié à Pi Network</div><div style={{fontSize:10,color:"#dc2626",background:"#fef2f2",border:"1px solid #fecaca",padding:8,borderRadius:8,fontWeight:800}}>⚠️ Gargoura Digital Bank ne demande JAMAIS votre Phrase Secrète ou Clé Secrète. Ne partagez jamais vos 24 mots.</div><input value={piAddr} onChange={e=>setPiAddr(e.target.value)} placeholder="Adresse publique Pi (commence par G...)" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input value={piUser} onChange={e=>setPiUser(e.target.value)} placeholder="Nom d'utilisateur Pi Network" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Vérifier Statut KYC Pi Officiel • {gdb.slice(0,8)}</button><div style={{fontSize:9,color:"#64748b"}}>KYC = Statut officiel Pi Network • Si vous êtes KYC Pi, vous êtes KYC GDB automatiquement</div></div>)}
export function APIKeys({gdb}){
const [keys,setKeys]=useState([])
function genKey(){const k="gsk_"+Math.random().toString(36).slice(2,12)+"_"+gdb.slice(4,8); setKeys([...keys,k])}
return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Clés API Gargoura • Connexion Plateformes</div><button onClick={genKey} style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Générer Clé API • {gdb.slice(0,8)}</button>{keys.map(k=><div key={k} style={{fontSize:9,background:"#f1f5f9",padding:6,borderRadius:6,fontFamily:"monospace"}}>{k}</div>)}<div style={{fontSize:9,color:"#64748b"}}>Utilisez ces clés pour connecter GDB à autres plateformes • Pi SDK intégré</div></div>)}
export function AIAssistant(){const [q,setQ]=useState(""),[a,setA]=useState("Bonjour, je suis l'Assistant IA Intelligent Gargoura Digital Bank. Comment puis-je vous aider?"); return(<div style={{display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>🤖 Assistant IA Intelligent GDB</div><div style={{background:"#eff6ff",border:"1px solid #bfdbfe",padding:10,borderRadius:10,fontSize:11}}>{a}</div><div style={{display:"flex",gap:4}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Posez votre question..." style={{flex:1,padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button onClick={()=>setA("Merci pour votre question: "+q+" • GDB répond: Transactions instantanées ISO20022 • Pi 314159 USD • Support 24/7 (+235)92825262")} style={{padding:10,borderRadius:8,background:"#1e40af",color:"#fff",border:"none",fontWeight:800}}>Envoyer</button></div></div>)}
