// @ts-nocheck
"use client"
import { useState,useEffect } from "react"
const gen=()=> "GDB-"+new Date().getFullYear()+"-"+Math.floor(100000+Math.random()*900000)
const Z=["CEMAC","UEMOA","Dollar","Jordanie","Golfe","Moyen-Orient","International"]
const B={"CEMAC":["Afriland","UBA Tchad","BGFI"],"UEMOA":["BOA","Ecobank CIV"],"Dollar":["Chase USA","BofA"],"Jordanie":["Arab Bank JO"],"Golfe":["ADCB UAE","Al Rajhi"],"Moyen-Orient":["Bank Audi"],"International":["BNP","Deutsche","HSBC"]}
const POOLS=[["Pi/USDT","2.4M","12.5%"],["Pi/BTC","1.8M","10.2%"],["Pi/ETH","2.1M","11%"],["Pi/USDC","1.9M","9.8%"],["Pi/ADA","890K","13.2%"],["Pi/DOT","750K","14.1%"],["Pi/XLM","620K","8.5%"],["Pi/XRP","1.2M","9.2%"],["Pi/MATIC","980K","10.8%"],["Pi/BNB","1.5M","11.5%"],["Pi/AVA","430K","15%"],["Pi/TRX","560K","9%"],["Pi/XAF","3.2M","7.5%"],["Pi/XOF","2.8M","7.2%"],["Pi/EUR","2M","8%"],["Pi/NGN","1.1M","8.8%"],["Pi/AED","1.3M","9.5%"],["Pi/JOD","900K","8.2%"],["Pi/YUAN","1.6M","7.8%"],["Pi/ROUBLE","700K","11.2%"],["Pi/ROUPIE","650K","10.5%"]]
const TOK=["PI","BTC","ETH","USDT","USDC","ADA","DOT","XLM","XRP","MATIC","BNB","AVA","TRX","XAF","XOF","EUR","NGN","AED","JOD","YUAN","ROUBLE","ROUPIE"]
const MON=["PI-314159","XAF","XOF","USD","EUR","AED","JOD","BTC","USDT"]
export default function Page(){
const [gdb,setGdb]=useState("GDB-2026-433422")
const [m,setM]=useState(""),[a,setA]=useState("accueil"),[tab,setTab]=useState("INTERNE"),[zone,setZone]=useState("CEMAC"),[vZone,setVZone]=useState("CEMAC"),[pool,setPool]=useState(POOLS[0]),[slip,setSlip]=useState("0.5%"),[from,setFrom]=useState("PI"),[to,setTo]=useState("USDT")
useEffect(()=>{try{let x=localStorage.getItem("gdb_account"); if(x) setGdb(x); else{let n=gen(); setGdb(n); localStorage.setItem("gdb_account",n)}}catch{}},[])
const funcs=["Transférer","Virement","Pi DEX","Convertir","Trading","AI Auto","Blockchain","Shopping","Portefeuilles","Automobile","Agrégation","Gestion"]
return(
<div style={{minHeight:"100vh",background:"#f8fafc",paddingBottom:110,fontFamily:"system-ui"}}>
<div style={{background:"#1e40af",color:"#fff",padding:10,position:"sticky",top:0,zIndex:30,borderBottom:"3px solid #facc15",fontWeight:900,fontSize:11}}>Gargoura • {gdb} • 1 PI=314159 USD</div>
<div style={{padding:12,display:"flex",flexDirection:"column",gap:10}}>
<div style={{background:"#fff",border:"2px solid #facc15",borderRadius:16,padding:12,textAlign:"center"}}><div style={{fontWeight:900}}>GARGOURA DIGITAL BANK</div><div style={{fontSize:9,color:"#64748b"}}>{gdb} • ISO20022 • PI 314159</div></div>
<div style={{background:"#1e3a8a",borderRadius:16,padding:12,color:"#fff"}}><div style={{fontSize:11}}>Solde Total • {gdb.slice(0,10)}</div><div style={{fontWeight:900,fontSize:20,marginTop:4}}>1 PI = 314 159,00 USD</div><div style={{display:"flex",gap:6,marginTop:10}}><button onClick={()=>setM("transferer")} style={{flex:1,background:"#16a34a",color:"#fff",border:"none",borderRadius:20,padding:9,fontWeight:800}}>Envoyer</button><button style={{flex:1,background:"#fff",color:"#1e3a8a",border:"none",borderRadius:20,padding:9,fontWeight:800}}>Recevoir</button></div></div>
<div style={{background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,padding:10}}><div style={{fontWeight:900,fontSize:12}}>Fonctionnalités Courantes • 12</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6,marginTop:8}}>{funcs.map(f=><button key={f} onClick={()=>setM(f.toLowerCase().replace(" ",""))} style={{border:"1px solid #e2e8f0",background:"#fff",borderRadius:10,padding:8,fontSize:9,fontWeight:700}}>{f}</button>)}</div></div>
</div>
{m && (<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",zIndex:50,display:"flex",alignItems:"flex-end"}}><div style={{background:"#f8fafc",width:"100%",borderRadius:"16px 16px 0 0",padding:10,maxHeight:"92vh",overflowY:"auto",borderTop:"3px solid #facc15"}}>
<div style={{display:"flex",justifyContent:"space-between",background:"#1e40af",color:"#fff",padding:8,borderRadius:10}}><div style={{fontWeight:900,fontSize:10}}>{gdb} • {m}</div><button onClick={()=>{setM(""); setA("accueil")}} style={{border:"none",background:"rgba(255,255,255,0.2)",color:"#fff",borderRadius:20,width:26,height:26}}>X</button></div>

{m.includes("transf") && (<div style={{background:"#fff",borderRadius:12,padding:10,marginTop:8,display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4}}><button onClick={()=>setTab("INTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="INTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="INTERNE"?"#dbeafe":"#fff",fontWeight:800,fontSize:10}}>P2P INTERNE</button><button onClick={()=>setTab("EXTERNE")} style={{flex:1,padding:8,borderRadius:10,border:tab==="EXTERNE"?"2px solid #1e40af":"1px solid #e2e8f0",background:tab==="EXTERNE"?"#dbeafe":"#fff",fontWeight:800,fontSize:10}}>P2P EXTERNE</button></div>
{tab==="INTERNE"?(<div style={{display:"flex",flexDirection:"column",gap:6}}><input placeholder="Numéro du Compte Bancaire" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(mm=><option key={mm}>{mm}</option>)}</select><input placeholder="Montant à envoyer" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input placeholder="Motif (Optionnel)" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Envoyer</button><div style={{fontSize:9,color:"#16a34a",background:"#f0fdf4",padding:6,borderRadius:6,textAlign:"center"}}>Les transactions sont instantanées et interopérables.</div></div>):(<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map(z=><button key={z} onClick={()=>setZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:zone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:zone===z?"#1e40af":"#fff",color:zone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{B[zone].map(b=><option key={b}>{b}</option>)}</select><input placeholder="Entrer le numéro de compte" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(mm=><option key={mm}>{mm}</option>)}</select><input placeholder="Le montant à transférer" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Transférer Vers Banque Externe</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>Transfert instantané via système interopérable - ISO20022 SWIFT SEPA</div></div>)}
</div>)}

{m.includes("virement") && (<div style={{background:"#fff",borderRadius:12,padding:10,marginTop:8,display:"flex",flexDirection:"column",gap:6}}><div style={{fontWeight:900,fontSize:12}}>Virement • ISO20022 SWIFT SEPA</div><div style={{display:"flex",gap:4,overflowX:"auto"}}>{Z.map(z=><button key={z} onClick={()=>setVZone(z)} style={{whiteSpace:"nowrap",padding:"6px 10px",borderRadius:20,border:vZone===z?"2px solid #1e40af":"1px solid #e2e8f0",background:vZone===z?"#1e40af":"#fff",color:vZone===z?"#fff":"#000",fontSize:9,fontWeight:800}}>{z}</button>)}</div><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{B[vZone].map(b=><option key={b}>{b}</option>)}</select><input placeholder="Entrer le numéro de compte" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><select style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}>{MON.map(mm=><option key={mm}>{mm}</option>)}</select><input placeholder="Le montant à transférer" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><input placeholder="Motif (Optionnel)" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Traiter l'opération</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>Le Virement est instantané dans le système interopérable.</div></div>)}

{m.includes("pidex") && (<div style={{background:"#fff",borderRadius:12,padding:10,marginTop:8,display:"flex",flexDirection:"column",gap:8}}><div style={{fontWeight:900}}>Pi DEX - AMM</div><div style={{fontSize:9,color:"#64748b"}}>PiCoin comme référence • Frais 0.3% + {gdb} • Slip: 0.5%/1%/3%</div>
<div style={{background:"#f8fafc",border:"1px solid #e2e8f0",borderRadius:10,padding:8,display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:10,fontWeight:800}}>De</span><select value={from} onChange={e=>setFrom(e.target.value)} style={{padding:6,borderRadius:6,border:"1px solid #cbd5e1"}}>{TOK.map(tk=><option key={tk}>{tk}</option>)}</select></div><input placeholder="Montant" style={{padding:10,borderRadius:8,border:"1px solid #cbd5e1"}}/><div style={{display:"flex",justifyContent:"center"}}><div style={{background:"#1e40af",color:"#fff",borderRadius:20,width:28,height:28,display:"flex",alignItems:"center",justifyContent:"center"}}>↓</div></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:10,fontWeight:800}}>Vers</span><select value={to} onChange={e=>setTo(e.target.value)} style={{padding:6,borderRadius:6,border:"1px solid #cbd5e1"}}>{TOK.map(tk=><option key={tk}>{tk}</option>)}</select></div><div style={{display:"flex",gap:4}}>{["0.5%","1%","3%"].map(s=><button key={s} onClick={()=>setSlip(s)} style={{padding:"4px 8px",borderRadius:20,border:slip===s?"2px solid #1e40af":"1px solid #e2e8f0",background:slip===s?"#dbeafe":"#fff",fontSize:9,fontWeight:800}}>{s}</button>)}</div><button style={{padding:10,borderRadius:10,background:"#1e40af",color:"#fff",fontWeight:900,border:"none"}}>Swap via AMM {from}→{to} • {slip} • {gdb.slice(0,10)}</button><div style={{fontSize:9,color:"#1e40af",background:"#eff6ff",padding:6,borderRadius:6,textAlign:"center"}}>AMM instantané • interopérable • sécurisé de bout en bout</div></div>
<div style={{fontWeight:800,fontSize:11}}>Pools AMM • {POOLS.length} pools</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{POOLS.map(p=><button key={p[0]} onClick={()=>{setPool(p); setFrom(p[0].split("/")[0]); setTo(p[0].split("/")[1])}} style={{textAlign:"left",padding:8,borderRadius:10,border:pool[0]===p[0]?"2px solid #1e40af":"1px solid #e2e8f0",background:pool[0]===p[0]?"#dbeafe":"#fff"}}><div style={{fontWeight:900,fontSize:10}}>{p[0]}</div><div style={{fontSize:8,color:"#64748b"}}>Liq {p[1]} • APY {p[2]}</div><div style={{fontSize:7,background:"#1e40af",color:"#fff",borderRadius:8,padding:"2px 5px",width:"fit-content",marginTop:2}}>Pool</div></button>)}</div>
</div>)}

</div></div>)}
</div>
)
}
