// @ts-nocheck
"use client"
import { useState,useEffect } from "react"
import { Transferer,Virement,PiDex,Cartes,KYCComponent,APIKeys,AIAssistant } from "./Components"
const gen=()=> "GDB-"+new Date().getFullYear()+"-"+Math.floor(100000+Math.random()*900000)
const genRcv=()=> "GDB-RCV-"+Math.floor(10000000+Math.random()*90000000)
const ICONS={transferer:"💸",virement:"🏦",pidex:"🔄",convertir:"💱",trading:"📈",aiauto:"🤖",blockchain:"⛓️",shopping:"🛒",portefeuilles:"👛",automobile:"🚗",agregation:"🔗",gestion:"⚙️"}
const MENU=[
{title:"COMPTE & PROFIL",items:[["Accueil","tableau de bord","accueil"],["Mon Profil","gérer mon compte","profil"],["Portefeuilles","Crypto & Digital","portefeuilles"]]},
{title:"PAIEMENTS & TRANSFERTS",items:[["Transferts P2P","Interne/Externe","transferer"],["Virement","ISO20022","virement"],["Mobile Money","Local/Régional/Intl","mobilemoney"],["Paiements Factures","Eau Elec etc","factures"]]},
{title:"TRADING & INVESTISSEMENTS",items:[["Trading","10+ Paires","trading"],["PiDEX & AMM","Web3","pidex"],["Staking","10+ cryptos","staking"]]},
{title:"SERVICES BANCAIRES",items:[["Cartes Bancaires","Virtuelles/Physiques","cartes"],["E-commerce","10+ Plateformes","shopping"],["Automobile","18+ Marques","automobile"]]},
{title:"SECURITÉS & CONFORMITÉS",items:[["Sécurité","Protection","securite"],["Conformité","Normes Intl","conformite"],["KYC Pi Officiel","Adresse G...","kyc"],["Clés API","Connexion","api"],["Surveillance IA","Monitoring","surveillance"]]},
{title:"SUPPORT",items:[["Paramètres","Config","parametres"],["Aide & Support","24/7","support"],["Assistant IA","GDB IA","ai"]]}
]
export default function Page(){
const [gdb,setGdb]=useState("GDB-2026-433422"),[rcv,setRcv]=useState(""),[m,setM]=useState(""),[menuOpen,setMenuOpen]=useState(false),[tabBottom,setTabBottom]=useState("accueil"),[notif,setNotif]=useState(3),[logoErr,setLogoErr]=useState(false),[guide,setGuide]=useState(""),[cond,setCond]=useState(""),[pol,setPol]=useState("")
useEffect(()=>{
try{
let x=localStorage.getItem("gdb_account"); if(!x){x=gen(); localStorage.setItem("gdb_account",x)} setGdb(x)
let r=localStorage.getItem("gdb_receive_code"); if(!r){r=genRcv(); localStorage.setItem("gdb_receive_code",r)} setRcv(r)
let g=localStorage.getItem("gdb_guide"); if(g) setGuide(g); else setGuide("1. Créer compte GDB 2. Code réception permanent + QR 3. Envoyer/Recevoir instantané")
let c=localStorage.getItem("gdb_cond"); if(c) setCond(c); else setCond("Utilisation conforme ISO20022, frais 0.3% + GDB, transactions instantanées.")
let p=localStorage.getItem("gdb_pol"); if(p) setPol(p); else setPol("Données chiffrées localement, jamais partagées. GDB unique par appareil.")
// Pi SDK
let s=document.createElement("script"); s.src="https://sdk.minepi.com/pi-sdk.js"; s.onload=()=>{try{window.Pi && window.Pi.init({version:"2.0"}) }catch{}}; document.head.appendChild(s)
}catch{setGdb(gen()); setRcv(genRcv())}
},[])
function openMod(id){setM(id); setMenuOpen(false); if(id==="accueil"){setTabBottom("accueil"); setM("")} else setTabBottom(id)}
const funcs=[["transferer","Transférer"],["virement","Virement"],["pidex","Pi DEX"],["convertir","Convertir"],["trading","Trading"],["aiauto","AI Auto"],["blockchain","Blockchain"],["shopping","Shopping"],["portefeuilles","Portefeuilles"],["automobile","Automobile"],["agregation","Agrégation"],["gestion","Gestion"]]
const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(rcv+"|"+gdb+"|PI-314159")}`
return(
<div style={{minHeight:"100vh",background:"#f8fafc",fontFamily:"system-ui",paddingBottom:110}}>
<div style={{background:"#1e40af",color:"#fff",padding:"10px 12px",position:"sticky",top:0,zIndex:30,borderBottom:"3px solid #facc15",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={()=>setMenuOpen(true)} style={{background:"#facc15",color:"#1e40af",border:"none",borderRadius:8,padding:"6px 10px",fontWeight:900}}>☰</button><div style={{fontWeight:900,fontSize:10}}>{gdb.slice(0,10)} • PI 314159</div></div>
<div style={{display:"flex",alignItems:"center",gap:6}}><button title="Langues Monde" style={{background:"rgba(255,255,255,0.2)",border:"none",borderRadius:20,width:28,height:28}}>🌍</button><button onClick={()=>openMod("profil")} style={{background:"rgba(255,255,255,0.2)",border:"none",borderRadius:20,width:28,height:28}}>👤</button><button onClick={()=>openMod("notifications")} style={{background:"rgba(255,255,255,0.2)",border:"none",borderRadius:20,width:28,height:28,position:"relative"}}>🔔{notif>0 && <span style={{position:"absolute",top:-4,right:-4,background:"#ef4444",color:"#fff",borderRadius:10,padding:"1px 4px",fontSize:8}}>{notif}</span>}</button></div>
</div>
<div style={{padding:12,display:"flex",flexDirection:"column",gap:10}}>
<div style={{background:"#fff",border:"2px solid #facc15",borderRadius:20,padding:14,display:"flex",flexDirection:"column",alignItems:"center"}}>{!logoErr?(<img src="/logo.png" alt="GDB" onError={()=>setLogoErr(true)} style={{width:70,height:70,borderRadius:35,border:"3px solid #facc15",objectFit:"cover"}} />):(<div style={{width:70,height:70,borderRadius:35,background:"#1e3a8a",border:"3px solid #facc15",display:"flex",alignItems:"center",justifyContent:"center",color:"#facc15",fontWeight:900}}>GDB</div>)}<div style={{fontWeight:900,marginTop:6,fontSize:14}}>GARGOURA DIGITAL BANK</div><div style={{fontSize:9,color:"#64748b"}}>{gdb} • ISO20022 • Couverture Mondiale 🌍</div></div>
<div style={{background:"#1e3a8a",borderRadius:16,padding:12,color:"#fff"}}><div style={{fontSize:11}}>Solde Total • {gdb}</div><div style={{fontWeight:900,fontSize:20,marginTop:4}}>1 PI = 314 159,00 USD</div><div style={{fontSize:9,color:"#86efac",marginTop:4}}>Code Réception: {rcv} • Stockage permanent téléphone</div><div style={{display:"flex",gap:6,marginTop:10}}><button onClick={()=>openMod("transferer")} style={{flex:1,background:"#16a34a",color:"#fff",border:"none",borderRadius:20,padding:9,fontWeight:800}}>Envoyer</button><button onClick={()=>openMod("recevoir")} style={{flex:1,background:"#fff",color:"#1e3a8a",border:"none",borderRadius:20,padding:9,fontWeight:800}}>Recevoir QR</button></div></div>
<div style={{background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,padding:10}}><div style={{fontWeight:900,fontSize:12}}>Fonctionnalités Courantes • 12 avec icônes</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6,marginTop:8}}>{funcs.map(([id,label])=><button key={id} onClick={()=>openMod(id)} style={{border:"1px solid #e2e8f0",background:"#fff",borderRadius:10,padding:8,display:"flex",flexDirection:"column",alignItems:"center",gap:2}}><div style={{fontSize:16}}>{ICONS[id]}</div><div style={{fontSize:8,fontWeight:800}}>{label}</div></button>)}</div></div>
</div>
<div style={{position:"fixed",bottom:0,left:0,right:0,background:"#fff",borderTop:"3px solid #facc15",zIndex:40,display:"flex",justifyContent:"space-around",padding:"6px 2px"}}>
<button onClick={()=>openMod("accueil")} style={{border:"none",background:"none",fontSize:8,color:tabBottom==="accueil"?"#1e40af":"#64748b",display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{fontSize:16}}>🏠</div>Accueil</button>
<button onClick={()=>openMod("transferer")} style={{border:"none",background:"none",fontSize:8,color:tabBottom==="transferer"?"#1e40af":"#64748b",display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{fontSize:16}}>💼</div>Services</button>
<button onClick={()=>openMod("pidex")} style={{border:"none",background:"none",fontSize:8,color:tabBottom==="pidex"?"#1e40af":"#64748b",display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{fontSize:16}}>🚀</div>Innovation</button>
<button onClick={()=>openMod("portefeuilles")} style={{border:"none",background:"none",fontSize:8,color:tabBottom==="portefeuilles"?"#1e40af":"#64748b",display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{fontSize:16}}>👛</div>Wallet</button>
<button onClick={()=>openMod("securite")} style={{border:"none",background:"none",fontSize:8,color:tabBottom==="securite"?"#1e40af":"#64748b",display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{fontSize:16}}>🛡️</div>Sécurité</button>
<button onClick={()=>openMod("support")} style={{border:"none",background:"none",fontSize:8,color:tabBottom==="support"?"#1e40af":"#64748b",display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{fontSize:16}}>❓</div>Support</button>
</div>
{menuOpen && (<div style={{position:"fixed",inset:0,zIndex:60,display:"flex"}}><div onClick={()=>setMenuOpen(false)} style={{flex:1,background:"rgba(0,0,0,0.5)"}}></div><div style={{width:"84%",maxWidth:360,background:"#fff",height:"100%",overflowY:"auto",borderRight:"3px solid #facc15"}}><div style={{background:"#1e40af",color:"#fff",padding:12,position:"sticky",top:0}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{fontWeight:900}}>Menu Principal</div><button onClick={()=>setMenuOpen(false)} style={{background:"rgba(255,255,255,0.2)",border:"none",color:"#fff",borderRadius:20,width:28,height:28}}>X</button></div><div style={{fontSize:9,color:"#facc15",marginTop:4}}>{gdb} • Toutes fonctionnalités GDB</div></div><div style={{padding:8,display:"flex",flexDirection:"column",gap:12}}>{MENU.map(sec=><div key={sec.title}><div style={{fontWeight:900,fontSize:9,color:"#1e40af",background:"#dbeafe",padding:"5px 8px",borderRadius:6}}>{sec.title}</div><div style={{display:"flex",flexDirection:"column",gap:4,marginTop:4}}>{sec.items.map(it=><button key={it[0]} onClick={()=>openMod(it[2])} style={{textAlign:"left",border:"1px solid #e2e8f0",background:"#fff",borderRadius:8,padding:"7px 8px"}}><div style={{fontWeight:800,fontSize:10}}>{it[0]}</div><div style={{fontSize:8,color:"#64748b"}}>{it[1]}</div></button>)}</div></div>)}</div></div></div>)}
{m && (<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.55)",zIndex:70,display:"flex",alignItems:"flex-end"}}><div style={{background:"#f8fafc",width:"100%",borderRadius:"16px 16px 0 0",padding:10,maxHeight:"92vh",overflowY:"auto",borderTop:"3px solid #facc15"}}><div style={{display:"flex",justifyContent:"space-between",background:"#1e40af",color:"#fff",padding:8,borderRadius:10}}><div style={{fontWeight:900,fontSize:10}}>{gdb} • {m} • PI 314159</div><button onClick={()=>setM("")} style={{border:"none",background:"rgba(255,255,255,0.2)",color:"#fff",borderRadius:20,width:26,height:26}}>X</button></div><div style={{background:"#fff",borderRadius:12,padding:10,marginTop:8}}>
{m==="transferer" && <Transferer gdb={gdb} />}
{m==="virement" && <Virement gdb={gdb} />}
{m==="pidex" && <PiDex gdb={gdb} />}
{m==="cartes" && <Cartes gdb={gdb} rcv={rcv} />}
{m==="kyc" && <KYCComponent gdb={gdb} />}
{m==="api" && <APIKeys gdb={gdb} />}
{m==="ai" && <AIAssistant />}
{m==="recevoir" && (<div style={{display:"flex",flexDirection:"column",gap:8,alignItems:"center"}}><div style={{fontWeight:900}}>Recevoir • QR Code Permanent</div><img src={qrUrl} alt="QR" style={{width:180,height:180,border:"3px solid #facc15",borderRadius:12}}/><div style={{background:"#1e40af",color:"#fff",padding:10,borderRadius:8,fontWeight:900,fontSize:10}}>{rcv}</div><div style={{fontSize:9,color:"#64748b",textAlign:"center"}}>QR lié au compte {gdb} • Stocké définitivement dans stockage téléphone • Partage pour paiement</div><div style={{fontSize:9,background:"#f0fdf4",padding:6,borderRadius:6}}>Adresse Pi: G... + Username Pi pour KYC • GDB {gdb}</div></div>)}
{m==="notifications" && (<div><div style={{fontWeight:900}}>🔔 Notifications Officielles GDB</div><div style={{fontSize:11,marginTop:8,display:"flex",flexDirection:"column",gap:6}}><div style={{background:"#eff6ff",padding:8,borderRadius:8}}>📢 Annonce: Pi DEX 10+ paires actives • APY jusqu'a 15%</div><div style={{background:"#f0fdf4",padding:8,borderRadius:8}}>✅ Opération: Virement instantané ISO20022 réussi • {gdb.slice(0,8)}</div><div style={{background:"#fef3c7",padding:8,borderRadius:8}}>⚠️ KYC: Liez votre adresse G... pour validation officielle Pi</div></div></div>)}
{m==="support" && (<div><div style={{fontWeight:900}}>Support 24H/24 7J/7 • Admin Editable</div><div style={{marginTop:8,display:"flex",flexDirection:"column",gap:6,fontSize:11}}><div>📞 Interne: (+235) 92 82 52 62</div><div>💬 WhatsApp: (+235) 66 78 75 46</div><div>📧 gargouradigitalbank@gmail.com</div><div style={{marginTop:8}}><div style={{fontWeight:800}}>Guide de Démarrage (Admin editable)</div><textarea value={guide} onChange={e=>{setGuide(e.target.value); localStorage.setItem("gdb_guide",e.target.value)}} style={{width:"100%",padding:8,borderRadius:8,border:"1px solid #cbd5e1",fontSize:10}} rows={3}></textarea></div><div><div style={{fontWeight:800}}>Conditions d'utilisation (Admin editable)</div><textarea value={cond} onChange={e=>{setCond(e.target.value); localStorage.setItem("gdb_cond",e.target.value)}} style={{width:"100%",padding:8,borderRadius:8,border:"1px solid #cbd5e1",fontSize:10}} rows={3}></textarea></div><div><div style={{fontWeight:800}}>Politique Confidentialité (Admin editable)</div><textarea value={pol} onChange={e=>{setPol(e.target.value); localStorage.setItem("gdb_pol",e.target.value)}} style={{width:"100%",padding:8,borderRadius:8,border:"1px solid #cbd5e1",fontSize:10}} rows={3}></textarea></div></div></div>)}
{m==="securite" && (<div><div style={{fontWeight:900}}>Sécurité & Conformités Réglementaires</div><div style={{fontSize:10,marginTop:6,display:"flex",flexDirection:"column",gap:4}}><div>• KYC/AML FATF • ISO20022 SWIFT SEPA</div><div>• Chiffrement bout en bout • Surveillance IA</div><div>• Normes CEMAC UEMOA Golfe International</div><button onClick={()=>openMod("kyc")} style={{padding:8,borderRadius:8,background:"#1e40af",color:"#fff",border:"none",fontWeight:800,marginTop:6}}>Faire KYC Pi Officiel (Adresse G...)</button><button onClick={()=>openMod("api")} style={{padding:8,borderRadius:8,background:"#fff",border:"1px solid #1e40af",color:"#1e40af",fontWeight:800}}>Générer Clés API</button></div></div>)}
{(m==="accueil"||m==="profil"||m==="portefeuilles"||m==="parametres"||m==="cartes") && m!=="cartes" && (<div style={{textAlign:"center",color:"#64748b",fontSize:12}}>Module {m} • {gdb} • {tabBottom}</div>)}
</div></div></div>)}
</div>
) 
}
