// Gargoura Digital Bank - Traductions Mondiales
// Ce fichier centralise TOUTES les langues pour alléger page.tsx

export type Lang = 'fr' | 'en' | 'ar' | 'es' | 'zh' | 'ha'

export const translations: Record<Lang, any> = {
  fr: {
    menu:'Menu Principal', sub:'Toutes les fonctionnalités Gargoura Digital Bank',
    comptes:'COMPTES & PROFIL', accueil:'Accueil', dash:'Tableau de bord',
    profil:'Mon Profil', gerer:'Gérer mon compte',
    wallet:'Portefeuilles', crypto:'Crypto & Digital',
    pay:'PAIEMENTS & TRANSFERTS', p2p:'Transferts P2P', inter:'Interne & International',
    mobile:'Mobile Money', cemac:'Zone CEMAC & UEMOA',
    fact:'Paiement Factures', eau:'Eau, Électricité, etc.',
    conv:'Convertisseur', dev:'93 devises mondiales',
    trading:'TRADING & INVESTISSEMENTS', tpi:'Trading Pi', paires:'10 paires en temps réel',
    dex:'Pi DEX & AMM', web3:'Échange décentralisé Web 3.0',
    staking:'Staking Crypto', cryptos:'12 cryptomonnaies',
    token:'Token GDB', prepa:'Préparation Pi Network',
    voyage:'VOYAGE, GASTRONOMIE & SERVICES PUBLICS', res:'Réservations premium', vol:'Vols, hôtels et restaurants en π',
    gov:'Services gouvernementaux Tchad', dem:'Démarches et frais préparatoires',
    douane:'Douane automatique', estim:"Estimation des frais d'importation",
    bank:'SERVICES BANCAIRES', cartes:'Cartes Bancaires', virt:'Virtuelles & Physiques',
    ecommerce:'E-Commerce', plat:'8 plateformes mondiales',
    auto:'Partenariat Automobile', marques:'18 marques disponibles',
    secu:'SÉCURITÉ & CONFORMITÉ', sec:'Sécurité', prot:'Protection avancée',
    conf:'Conformité', normes:'Normes internationales',
    surv:'Surveillance IA', mon:'Monitoring intelligent',
    supp:'SUPPORT & PARAMÈTRES', param:'Paramètres', config:'Configuration',
    aide:'Aide & Support', centre:"Centre d'assistance",
    assistant:'Assistant IA Gargoura', iaDesc:'Intelligence artificielle pour surveiller, optimiser et sécuriser toutes vos opérations bancaires en temps réel',
    voir:'Voir la Surveillance IA', contact:'Contact Gargoura Digital Bank',
    langLabel:'🌐 Langue'
  },
  en: {
    menu:'Main Menu', sub:'All Gargoura Digital Bank features',
    comptes:'ACCOUNTS & PROFILE', accueil:'Home', dash:'Dashboard',
    profil:'My Profile', gerer:'Manage my account',
    wallet:'Wallets', crypto:'Crypto & Digital',
    pay:'PAYMENTS & TRANSFERS', p2p:'P2P Transfers', inter:'Domestic & International',
    mobile:'Mobile Money', cemac:'CEMAC & UEMOA Zone',
    fact:'Bill Payment', eau:'Water, Electricity, etc.',
    conv:'Converter', dev:'93 world currencies',
    trading:'TRADING & INVESTMENTS', tpi:'Pi Trading', paires:'10 real-time pairs',
    dex:'Pi DEX & AMM', web3:'Web 3.0 Decentralized Exchange',
    staking:'Crypto Staking', cryptos:'12 cryptocurrencies',
    token:'GDB Token', prepa:'Pi Network Preparation',
    voyage:'TRAVEL, FOOD & PUBLIC SERVICES', res:'Premium Bookings', vol:'Flights, hotels & restaurants in π',
    gov:'Chad Government Services', dem:'Procedures & preparatory fees',
    douane:'Automatic Customs', estim:'Import fees estimation',
    bank:'BANKING SERVICES', cartes:'Bank Cards', virt:'Virtual & Physical',
    ecommerce:'E-Commerce', plat:'8 global platforms',
    auto:'Automotive Partnership', marques:'18 brands available',
    secu:'SECURITY & COMPLIANCE', sec:'Security', prot:'Advanced protection',
    conf:'Compliance', normes:'International standards',
    surv:'AI Surveillance', mon:'Intelligent monitoring',
    supp:'SUPPORT & SETTINGS', param:'Settings', config:'Configuration',
    aide:'Help & Support', centre:'Help center',
    assistant:'Gargoura AI Assistant', iaDesc:'AI to monitor, optimize and secure all your banking operations in real time',
    voir:'View AI Surveillance', contact:'Contact Gargoura Digital Bank',
    langLabel:'🌐 Language'
  },
  ar: {
    menu:'القائمة الرئيسية', sub:'جميع ميزات بنك غارغورا الرقمي',
    comptes:'الحسابات والملف', accueil:'الرئيسية', dash:'لوحة التحكم',
    profil:'ملفي', gerer:'إدارة حسابي',
    wallet:'المحافظ', crypto:'تشفير ورقمي',
    pay:'المدفوعات والتحويلات', p2p:'تحويلات P2P', inter:'داخلي ودولي',
    mobile:'أموال الهاتف', cemac:'منطقة سيماك ويوموا',
    fact:'دفع الفواتير', eau:'ماء، كهرباء، إلخ',
    conv:'محول', dev:'93 عملة عالمية',
    trading:'التداول والاستثمار', tpi:'تداول Pi', paires:'10 أزواج في الوقت الفعلي',
    dex:'Pi DEX & AMM', web3:'تبادل لامركزي ويب 3.0',
    staking:'تخزين العملات', cryptos:'12 عملة مشفرة',
    token:'رمز GDB', prepa:'إعداد شبكة Pi',
    voyage:'السفر والخدمات', res:'حجوزات مميزة', vol:'رحلات وفنادق ومطاعم بـ π',
    gov:'خدمات حكومة تشاد', dem:'إجراءات ورسوم تحضيرية',
    douane:'جمارك تلقائية', estim:'تقدير رسوم الاستيراد',
    bank:'الخدمات المصرفية', cartes:'البطاقات المصرفية', virt:'افتراضية ومادية',
    ecommerce:'التجارة الإلكترونية', plat:'8 منصات عالمية',
    auto:'شراكة السيارات', marques:'18 علامة متاحة',
    secu:'الأمن والامتثال', sec:'الأمان', prot:'حماية متقدمة',
    conf:'الامتثال', normes:'معايير دولية',
    surv:'مراقبة الذكاء الاصطناعي', mon:'مراقبة ذكية',
    supp:'الدعم والإعدادات', param:'الإعدادات', config:'التكوين',
    aide:'المساعدة والدعم', centre:'مركز المساعدة',
    assistant:'مساعد غارغورا الذكي', iaDesc:'ذكاء اصطناعي لمراقبة وتحسين وتأمين جميع عملياتك المصرفية في الوقت الفعلي',
    voir:'عرض المراقبة الذكية', contact:'اتصل ببنك غارغورا الرقمي',
    langLabel:'🌐 اللغة'
  },
  es: {
    menu:'Menú Principal', sub:'Todas las funciones de Gargoura Digital Bank',
    comptes:'CUENTAS Y PERFIL', accueil:'Inicio', dash:'Panel',
    profil:'Mi Perfil', gerer:'Gestionar mi cuenta',
    wallet:'Billeteras', crypto:'Cripto y Digital',
    pay:'PAGOS Y TRANSFERENCIAS', p2p:'Transferencias P2P', inter:'Nacional e Internacional',
    mobile:'Dinero Móvil', cemac:'Zona CEMAC y UEMOA',
    fact:'Pago de Facturas', eau:'Agua, Electricidad, etc.',
    conv:'Convertidor', dev:'93 monedas mundiales',
    trading:'TRADING E INVERSIONES', tpi:'Trading Pi', paires:'10 pares en tiempo real',
    dex:'Pi DEX & AMM', web3:'Intercambio descentralizado Web 3.0',
    staking:'Staking Cripto', cryptos:'12 criptomonedas',
    token:'Token GDB', prepa:'Preparación Pi Network',
    voyage:'VIAJE Y SERVICIOS', res:'Reservas premium', vol:'Vuelos, hoteles y restaurantes en π',
    gov:'Servicios Gubernamentales Chad', dem:'Trámites y tasas preparatorias',
    douane:'Aduana automática', estim:'Estimación de gastos de importación',
    bank:'SERVICIOS BANCARIOS', cartes:'Tarjetas Bancarias', virt:'Virtuales y Físicas',
    ecommerce:'E-Commerce', plat:'8 plataformas mundiales',
    auto:'Asociación Automotriz', marques:'18 marcas disponibles',
    secu:'SEGURIDAD Y CUMPLIMIENTO', sec:'Seguridad', prot:'Protección avanzada',
    conf:'Conformidad', normes:'Normas internacionales',
    surv:'Vigilancia IA', mon:'Monitoreo inteligente',
    supp:'SOPORTE Y CONFIGURACIÓN', param:'Parámetros', config:'Configuración',
    aide:'Ayuda y Soporte', centre:'Centro de asistencia',
    assistant:'Asistente IA Gargoura', iaDesc:'IA para monitorear, optimizar y asegurar todas tus operaciones bancarias en tiempo real',
    voir:'Ver Vigilancia IA', contact:'Contacto Gargoura Digital Bank',
    langLabel:'🌐 Idioma'
  },
  zh: {
    menu:'主菜单', sub:'Gargoura数字银行的所有功能',
    comptes:'账户与资料', accueil:'首页', dash:'仪表板',
    profil:'我的资料', gerer:'管理我的账户',
    wallet:'钱包', crypto:'加密与数字',
    pay:'支付与转账', p2p:'P2P转账', inter:'国内与国际',
    mobile:'手机支付', cemac:'中非与西非区',
    fact:'账单支付', eau:'水、电等',
    conv:'转换器', dev:'93种世界货币',
    trading:'交易与投资', tpi:'Pi交易', paires:'10个实时交易对',
    dex:'Pi DEX & AMM', web3:'Web 3.0去中心化交易',
    staking:'加密质押', cryptos:'12种加密货币',
    token:'GDB代币', prepa:'Pi网络准备',
    voyage:'旅行与公共服务', res:'高级预订', vol:'航班、酒店和餐厅以π支付',
    gov:'乍得政府服务', dem:'手续和预备费用',
    douane:'自动海关', estim:'进口费用估算',
    bank:'银行服务', cartes:'银行卡', virt:'虚拟与实体',
    ecommerce:'电子商务', plat:'8个全球平台',
    auto:'汽车合作', marques:'18个可用品牌',
    secu:'安全与合规', sec:'安全', prot:'高级保护',
    conf:'合规', normes:'国际标准',
    surv:'AI监控', mon:'智能监控',
    supp:'支持与设置', param:'设置', config:'配置',
    aide:'帮助与支持', centre:'帮助中心',
    assistant:'Gargoura AI助手', iaDesc:'人工智能实时监控、优化和保护您的所有银行操作',
    voir:'查看AI监控', contact:'联系Gargoura数字银行',
    langLabel:'🌐 语言'
  },
  ha: {
    menu:'Babban Menu', sub:'Dukkan ayyukan Gargoura Digital Bank',
    comptes:'ASUSU & BAYANI', accueil:'Gida', dash:'Allo',
    profil:'Bayana', gerer:'Sarrafa asusuna',
    wallet:'Wallets', crypto:'Crypto & Digital',
    pay:'BIYA & CANJA WURI', p2p:'Canja wurin P2P', inter:'Ciki & Waje',
    mobile:'Kudin waya', cemac:'Yankin CEMAC & UEMOA',
    fact:'Biyan Kuɗi', eau:'Ruwa, Wuta, da sauransu',
    conv:'Mai canzawa', dev:'Kudade 93 na duniya',
    trading:'KASUWANCI & ZUBA JARI', tpi:'Kasuwancin Pi', paires:'Manya 10 a ainihin lokaci',
    dex:'Pi DEX & AMM', web3:'Musayar Web 3.0',
    staking:'Staking Crypto', cryptos:'12 cryptocurrencies',
    token:'Token GDB', prepa:'Shirin Pi Network',
    voyage:'TAFIYA & HIDIMOMIN JAMA\'A', res:'Ajiyar kuɗi masu kyau', vol:'Jiragen sama, otal da gidajen abinci a π',
    gov:'Ayyukan Gwamnati Chadi', dem:'Hanyoyi da kudaden shiri',
    douane:'Kwastam ta atomatik', estim:'Kiyasin kuɗin shigo da kaya',
    bank:'AYYUKAN BANKI', cartes:'Katunan Banki', virt:'Virtual & Physical',
    ecommerce:'E-Kasuwanci', plat:'Dandamali 8 na duniya',
    auto:'Haɗin gwiwar Mota', marques:'Samfura 18 akwai',
    secu:'TSARO & BIN DOKA', sec:'Tsaro', prot:'Kariya ta ci gaba',
    conf:'Bin doka', normes:'Ka\'idojin duniya',
    surv:'Kula da AI', mon:'Kula da hankali',
    supp:'TALLAFI & SAITUNA', param:'Saituna', config:'Kanfigareshan',
    aide:'Taimako & Tallafi', centre:'Cibiyar taimako',
    assistant:'Mataimakin AI Gargoura', iaDesc:'AI don sa ido, ingantawa da amintar da duk ayyukan bankin ku a ainihin lokaci',
    voir:'Duba Kula da AI', contact:'Tuntuɓi Gargoura Digital Bank',
    langLabel:'🌐 Harshe'
  }
}

export const langOptions = [
  {k:'fr' as Lang, f:'🇫🇷 Français'},
  {k:'en' as Lang, f:'🇬🇧 English'},
  {k:'ar' as Lang, f:'🇸🇦 العربية'},
  {k:'es' as Lang, f:'🇪🇸 Español'},
  {k:'zh' as Lang, f:'🇨🇳 中文'},
  {k:'ha' as Lang, f:'🇳🇪 Hausa'},
]

export function getT(lang:string){
  return translations[lang as Lang] || translations.fr
    }
